// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QRA.Repositories.Content;

namespace QRA.Migrations.Migrations
{
    [DbContext(typeof(QRAContext))]
    [Migration("20180814055136_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("QRA")
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QRA.Entities.Content.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUsuario");

                    b.Property<string>("Clave")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<byte>("Estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("SMALLDATETIME");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id", "IdUsuario")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("QRA.Entities.Content.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("TipoIdentificacion");
                });

            modelBuilder.Entity("QRA.Entities.Content.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("SMALLDATETIME");

                    b.Property<int>("IdTipoIdentificacion");

                    b.Property<string>("Identificacion")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Movil")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Nombres")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Telefono")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
